/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#74240b',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#c1c8ca',
        'on-primary-fixed': '#002115',
        'surface-dim': '#dbdad7',
        'on-tertiary-fixed-variant': '#41484a',
        'on-error-container': '#93000a',
        'on-primary-container': '#00402d',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        secondary: '#9e4227',
        tertiary: '#586062',
        'secondary-fixed-dim': '#ffb5a0',
        'surface-container-high': '#e9e8e5',
        'tertiary-container': '#9ba2a4',
        surface: '#faf9f6',
        'secondary-container': '#fe8b6a',
        error: '#ba1a1a',
        'on-secondary-fixed': '#3b0900',
        'surface-bright': '#faf9f6',
        'primary-fixed': '#86f8c8',
        'primary-fixed-dim': '#69dbad',
        'on-primary': '#ffffff',
        background: '#faf9f6',
        'on-surface-variant': '#3d4943',
        'on-tertiary-container': '#32393b',
        'on-background': '#1a1c1a',
        'primary-container': '#3eb489',
        'on-tertiary-fixed': '#161d1f',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e3e2e0',
        'inverse-primary': '#69dbad',
        'surface-container-highest': '#e3e2e0',
        'inverse-surface': '#2f312f',
        'outline-variant': '#bccac1',
        'secondary-fixed': '#ffdbd1',
        'on-primary-fixed-variant': '#005139',
        outline: '#6d7a72',
        'on-secondary-fixed-variant': '#7e2b12',
        'surface-tint': '#006c4d',
        'surface-container-low': '#f4f3f1',
        'inverse-on-surface': '#f2f1ee',
        'surface-container': '#efeeeb',
        'tertiary-fixed': '#dde4e6',
        'on-surface': '#1a1c1a',
        primary: '#006c4d',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-padding-desktop': '40px',
        'card-gap': '16px',
        gutter: '24px',
        'container-padding-mobile': '20px',
        unit: '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'match-score': ['Sora', 'sans-serif'],
        'hero-stat': ['Sora', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'match-score': ['14px', { lineHeight: '14px', fontWeight: '700' }],
        'hero-stat': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      boxShadow: {
        ambient: '0 10px 30px rgba(45, 52, 70, 0.04)',
      },
    },
  },
  plugins: [],
};
